# Generated by Django 5.1.2 on 2024-11-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_webauthnkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthnkey',
            name='credential_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webauthnkey',
            name='credential_data',
            field=models.BinaryField(),
        ),
    ]
