# Generated by Django 5.1.2 on 2024-11-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_note_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
