# Generated by Django 5.1.2 on 2024-11-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webauthnkey',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='WebAuthnKey',
        ),
    ]
