# Generated by Django 5.1.2 on 2024-11-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_webauthnkey_user_delete_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='deadline',
        ),
    ]
