# Generated by Django 5.1.2 on 2024-11-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_note_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
